version: '3.9'

networks:
  lamp:

services:
  server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        - PHP_VERSION_SELECTED=${PHP_VERSION_SELECTED}
        - PHP_VERSION=${PHP_VERSION_SELECTED}
    container_name: '${APP_NAME}-server'
    ports:
      - '${APP_PORT}:80'
      - '${SSL_PORT}:443'
    working_dir: /var/www/
    environment:
      - 'DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASS}@db_server:3306/${MYSQL_DB}'
    volumes:
      - ./sources:/var/www/
      - ./docker/server/apache/sites-enabled:/etc/apache2/sites-enabled
      - ./docker/server/php/php.ini:/usr/local/etc/php/conf.d/extra-php-config.ini
      - ./docker/server/php/php-xdebug.ini:/usr/local/etc/php/conf.d/zz-xdebug-settings.ini
      - ./docker/server/certs:/var/www/certs
      - ./docker/logs:/var/www/logs
    networks:
      - lamp

  db_server:
    image: mariadb
    container_name: '${APP_NAME}-db'
    restart: always
    ports:
      - '${DB_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASS}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASS}'
      MYSQL_DATABASE: '${MYSQL_DB}'
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/db/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf
    healthcheck:
      test: mysqladmin ping -h ${IP_DB_SERVER} -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 5
    networks:
      - lamp

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${APP_NAME}-phpmyadmin
    restart: always
    ports:
      - '${PHPMYADMIN_PORT}:${APP_PORT}'
    environment:
      PMA_HOST: db_server
      UPLOAD_LIMIT: 1024M
    networks:
      - lamp

  redis:
    image: redis
    container_name: ${APP_NAME}-redis
    hostname: redis
    restart: 'on-failure'
    ports:
      - '${REDIS_PORT}:6379'
    networks:
      - lamp
volumes:
  db_data: